apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: mc
spec:
  # the number of GameServers to keep Ready or Allocated in this Fleet
  replicas: 5
  # defines how GameServers are organised across the cluster.
  # "Packed" (default) is aimed at dynamic Kubernetes clusters, such as cloud providers, wherein we want to bin pack
  # resources
  scheduling: Packed
  strategy:
    # "Recreate" terminates all non-allocated GameServers, and starts up a new set with the new details to replace them.
    type: Recreate
  template:
    # GameServer metadata
    metadata:
      labels:
        # GameServer lablel to match with GameServerAllocation
        game: mc
        edition: java
      annotations:
        external-dns.alpha.kubernetes.io/hostname: <DOMAIN>
        external-dns.alpha.kubernetes.io/gameserver-service: minecraft
    spec:
      container: mc-server # Minecraft server container name
      ports:
        - name: mc
          # "Dynamic" (default) the system allocates a free hostPort for the gameserver (default 7000-8000), for game clients to connect to
          portPolicy: Dynamic
          # The name of the container to open the port on. Defaults to the game server container if omitted or empty.
          container: mc-server
          # the port that is being opened on the game server process
          containerPort: 25565
          # Minecraft uses TCP to connect players
          protocol: TCP
      # Health checking for the running game server
      health:
        # Number of seconds after the container has started before health check is initiated.
        initialDelaySeconds: 300
        # If the `Health()` function doesn't get called at least once every period (seconds), then
        # the game server is not healthy.
        periodSeconds: 12
        # Minimum consecutive failures for the health probe to be considered failed after having succeeded.
        failureThreshold: 5
      template:
        spec:
          containers:
            - name: mc-server
              image: itzg/minecraft-server # Minecraft Java server image
              env: # Full list of ENV variables at https://github.com/itzg/docker-minecraft-server
                - name: EULA
                  value: "TRUE"
              volumeMounts:
                - mountPath: /data # shared vol with mc-load and mc-backup
                  name: world-vol
              ports:
              - containerPort: 25575 # exposes the RCON port to within the cluster from the pod's IP

            - name: mc-monitor
              image: saulmaldonado/agones-mc # monitor
              args:
                - monitor
                - --attempts=5 # matches spec.health.failureThreshold
                - --initial-delay=60s # matches spec.health.initialDelaySeconds
                - --interval=10s # below spec.health.periodSecond
                - --timeout=10s # matches interval
              imagePullPolicy: Always

            - name: mc-backup
              image: saulmaldonado/agones-mc # backup
              args:
                - backup
                - --gcp-bucket-name=agones-minecraft-mc-worlds # GCP Cloud storage bucket name for world archives
                - --backup-cron=0 */6 * * * # crontab for recurring backups. omiting flag will only run backup once
                - --initial-delay=60s # delay for mc-server to build world before scheduling backup jobs
              env:
                - name: NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name # GameServer ref for naming backup zip files
                - name: RCON_PASSWORD
                  value: minecraft # default rcon password. If provided RCON connection will be used to execute 'save-all' before a backup job.
                  # Change the rcon password when exposing RCON port outside the pod
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /data # shared vol with mc-server
                  name: world-vol

          volumes:
            - name: world-vol # shared vol between containers. will not persist bewteen restarts
